### ISSUE TITLE
Add an MIT license to this repo

### ISSUE THREAD

**Issue by abidurrahman11** [abidurrahman11/Pygame-Racing-Car#1]
**Instructions:**
First fork this repo to make your own copy. Then follow the steps below to add MIT license.

1. Navigate to the main page of the repository.
2. Above the list of files, select the Add file dropdown menu, then click + Create new file.
3. In the file name field, type LICENSE (with all caps).
4. Under the file name, click Choose a license template.
5. On the left side of the page, under "Add a license to your project," review the available licenses, then select MIT license from the list.
6. Click Review and submit.
7. Click Commit changes...

After adding the licence in forked repo make a pull request.

**Comment by P-Pole** [comment]
Hello @abidurrahman11,

If you do not mind - I can deal with this issue.

**Comment by abidurrahman11** [comment]
@brion4 you can start working on the issue
