### ISSUE TITLE
Make a new directory inside assets directory

### ISSUE THREAD

**Issue by abidurrahman11** [abidurrahman11/Pygame-Racing-Car#10]
Make a new directory called `cars` inside `assets` directory.
Leave a comment here and wait until you are assigned for the issue.

**Comment by viktoriussuwandi** [comment]
Hi [abidurrahman11](https://github.com/abidurrahman11), I think I can do this, please assign me

**Comment by abidurrahman11** [comment]
@viktoriussuwandi you can start working👋
