### ISSUE TITLE
Add PRs Welcome badge

### ISSUE THREAD

**Issue by abidurrahman11** [abidurrahman11/Pygame-Racing-Car#11]
In README file add a PRs Welcome badge as newcomers to open source are welcomed to contribute.
You can learn about adding the badges here: [PRs Welcome](https://makeapullrequest.com/)

Please leave a comment to be assigned for the task.

**Comment by viktoriussuwandi** [comment]
Hi [abidurrahman11](https://github.com/abidurrahman11), 
Do you mean badges like [this](https://img.shields.io/badge/contributions-welcome-blue) ?
I think I can do this, please assign me

**Comment by viktoriussuwandi** [comment]
Got it, you mean [this](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square) badges right ?
Please assign me

**Comment by abidurrahman11** [comment]
@viktoriussuwandi Best of luck

**Comment by abidurrahman11** [comment]
@viktoriussuwandi  I will unassign you if you are too late.
