### ISSUE TITLE
Remove unnecessary lines.

### ISSUE THREAD

**Issue by abidurrahman11** [abidurrahman11/Pygame-Racing-Car#25]
Remove unnecessary print statement from [cargame.py](https://github.com/abidurrahman11/Pygame-Racing-Car/blob/master/cargame.py) file.
Do not change anything else.

**Comment by fi1na** [comment]
Hello, can you please assign this issue to me?

**Comment by abidurrahman11** [comment]
Hi @fi1na , you are assigned. Good Luck!
