### ISSUE TITLE
change the font and position of score

### ISSUE THREAD

**Issue by abidurrahman11** [abidurrahman11/Pygame-Racing-Car#26]
Can you make the score looks prettier by using better font for this game? Also move the position of the score a little bit right to make it look better.
Your task is to make the score look better. Do not change anything else.

**Comment by yr1404** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by abidurrahman11** [comment]
Hi @yr1404 you are assigned!
Good luck

**Comment by yr1404** [comment]
@abidurrahman11 Can you add the hacktoberfest-accepted label ?

**Comment by abidurrahman11** [comment]
3rd one (Pixel Gamer) looks better.

**Comment by yr1404** [comment]
It seems to be a demo version of font which has watermark when used.
Here is a similar looking free font:  
![image](https://github.com/abidurrahman11/Pygame-Racing-Car/assets/106465753/e720c505-aa0e-4f07-905a-e5607aa5ef98)
