### ISSUE TITLE
Create a separate folder for car images

### ISSUE THREAD

**Issue by abidurrahman11** [abidurrahman11/Pygame-Racing-Car#34]
Create a new directory inside `assets` directory. Name the directory as `cars`.
The new path should look similar to the following: `Pygame-Racing-Car/assets/cars`

**Make sure you leave a comment on this issue and wait until you are assigned. Then you can create a PR.**

**Comment by phvanlie** [comment]
Hi @abidurrahman11 👋 
I am interested on this, can I work on this request?
Thank you
