### ISSUE TITLE
Add information about controls to pause menu

### ISSUE THREAD

**Issue by NickFranciscoOSU** [abidurrahman11/Pygame-Racing-Car#38]
Contribution
There is no information for the controls of the game. I would like to alleviate this issue by adding information about the controls (i.e. changing lanes, accelerating, and exiting the game) to the pause menu.

**Comment by abidurrahman11** [comment]
Hey @NickFranciscoOSU You're welcomed for contribution. Can you please provide detailed workplan for this issue?

**Comment by NickFranciscoOSU** [comment]
Work Plan

1. Scope: This update will add information for the controls of the game to the existing pause menu. 
2. Projected Timeline: 1 – 2 weeks.
3. Implementation: To implement this change I will create another function that draws information about controls to the screen below the Pause message. The message will show which button(s) change lanes, accelerate, pause the game, and exit the game. The function will then be called when the game is paused, similar to the game_pause_draw() function. 
4. Testing: Acceptance Testing will be used to ensure the game works as it did before and to test the new feature. 
5. Deployment: Once implementation and testing are complete, a pull request will be created with the updated feature.

**Comment by abidurrahman11** [comment]
Hey can start working. Good luck

**Comment by NickFranciscoOSU** [comment]
I finished adding information about the controls to the pause menu. 
I have two examples, one with a box surrounding the new controls message and one without. 
Do you have a preference or any requests before I create a pull request? 

![Pause with box](https://github.com/abidurrahman11/Pygame-Racing-Car/assets/122332006/a6dbe6fa-426e-4d79-9588-962a1eee0e7f)
![Pause no box](https://github.com/abidurrahman11/Pygame-Racing-Car/assets/122332006/921f1897-a11f-4036-8f87-1f75d28d453b)

**Comment by abidurrahman11** [comment]
Hey @NickFranciscoOSU 
Thanks for work. The first one looks better. You may also try to add different text color to find a good combination with background.

**Comment by NickFranciscoOSU** [comment]
Hey @abidurrahman11, I changed the text color to match the game over style. However, I am trying to create a pull request but I am getting an error that I do not have the correct access right, do you need to update my permission? I double checked my username and password for a HTTPS push and tried to push using SSH but I am still getting the same permission error.

**Comment by NickFranciscoOSU** [comment]
Hey @abidurrahman11, I am trying to create a pull request, but I am getting an error that I do not have the correct access rights to make a pull request. I tried to create a pull request using HTTPS, SSH, and GitHub desktop and all give me the same error, do you need to update my permissions before I can create a pull request? If not I will try and figure out what the problem is on my side, thank you.
