### ISSUE TITLE
Resize the screenshots on README and place the images in 1 row

### ISSUE THREAD

**Issue by abidurrahman11** [abidurrahman11/Pygame-Racing-Car#5]
Make the two screenshot little bit smaller in size and put the in the same row. 

**Instructions:**
1. Fork the repo
2. Resize the images
3. Do not delete the original images. Just upload resized images
4. Change original images by resized images
5. Update the README by placing two images in one row
6. Make Pull Request

**Make sure you leave a comment on this issue and wait until you are assigned. Then you can create a PR.**

**Comment by maynouf** [comment]
Could resizing the image using html tags like `<img src="car.png" alt="car" width="200"/>` work instead of resizing & reuploading the images?

**Comment by maynouf** [comment]
Anyways, I've tested it and it works. If you are interested in this approach, you can assign me the issue and I'll gladly make the PR.

First PR to an open source project btw :)

**Comment by Egnodia** [comment]
Assign me Pls  :)

**Comment by abidurrahman11** [comment]
Hey @maynouf you can start working on the project with your idea. Please make sure to add a little bit space between two images.
