### ISSUE TITLE
Move the images in a new directory

### ISSUE THREAD

**Issue by abidurrahman11** [abidurrahman11/Pygame-Racing-Car#8]
**What to do:**

1. Make a new directory `assets` in the repo
2. Move `car.png` and `otherCar.png` files in assets
3. now delete these two files from main directory
4. Go to `pygame.py` file
5. In line 27 and 32 you will find the variables are containing previous location of the images
6. Change these variable respectively with the new location. (As the images are now in `assets` folder)
7. Make sure to check if the game is loading the cars properly

**Make sure you leave a comment on this issue and wait until you are assigned. Then you can create a PR.**

**Comment by chachasoba** [comment]
could you assign this to me please? would like to try it as my first PR

**Comment by abidurrahman11** [comment]
Hey @chachasoba can you please assure me that you can handle this, as it will require you to test if the game works properly after changing the images to new directory.
Newcomers are always welcomed😍.

**Comment by chachasoba** [comment]
yes I will try my best to make it work.

**Comment by chachasoba** [comment]
How can I do a PR? I did not make a new branch but instead clone and committed the code to the forked master branch.

**Comment by achhayapathak** [comment]
is it still open?

**Comment by abidurrahman11** [comment]
best of luck @chachasoba
